name: Automated Testing only

on: [pull_request]

env:
  TAG: SanityCheck.${{ github.event.pull_request.user.login }}.${{ github.event.repository.pushed_at}}

jobs:
  run_Tests_UAT:
    name: Run_Tests_UAT
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: cerberus-action
      uses: cerberustesting/cerberus-github-action@v6
      with:
        host: https://jftl.cerberus-testing.fr
        campaign: SanityCheck
        apikey: ${{ secrets.APIKEY }}
        author: ${{ github.event.pull_request.user.login }}
        environment: UAT
        tag: ${TAG}
